In [2]:
import pandas as pd
import numpy as np

C:\Users\NOUR\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df = pd.read_csv('E:/NOUR/Documents/PFE/data/youtubers_df.csv')
df.head()

,Rank,Username,Categories,Suscribers,Country,Visits,Likes,Comments,Links
0,1,tseries,Música y baile,249500000.0,India,86200.0,2700.0,78.0,http://youtube.com/channel/UCq-Fj5jknLsUf-MWSy...
1,2,MrBeast,"Videojuegos, Humor",183500000.0,Estados Unidos,117400000.0,5300000.0,18500.0,http://youtube.com/channel/UCX6OQ3DkcsbYNE6H8u...
2,3,CoComelon,Educación,165500000.0,Unknown,7000000.0,24700.0,0.0,http://youtube.com/channel/UCbCmjCuTUZos6Inko4...
3,4,SETIndia,NaN,162600000.0,India,15600.0,166.0,9.0,http://youtube.com/channel/UCpEhnqL0y41EpW2TvW...
4,5,KidsDianaShow,"Animación, Juguetes",113500000.0,Unknown,3900000.0,12400.0,0.0,http://youtube.com/channel/UCk8GzjMOrta8yxDcKf...

In [6]:
df.isna().any()

Rank          False
Username      False
Categories     True
Suscribers    False
Country       False
Visits        False
Likes         False
Comments      False
Links         False
dtype: bool

In [5]:
df_categories_na_dropped = df.dropna(subset = ['Categories'])
# print(df_categories_na_dropped)
df_categories_na_dropped['Categories'] = df_categories_na_dropped['Categories'].apply(lambda x: x.split(','))

df_categories_na_dropped['Categories'] = df_categories_na_dropped['Categories'].apply(lambda x: [i.strip() for i in x] if isinstance(x, list) else x)
df_categories_na_dropped

# ! TODO debug code
df_categories_na_dropped['Categories'][1]

<ipython-input-5-717e63366304>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_categories_na_dropped['Categories'] = df_categories_na_dropped['Categories'].apply(lambda x: x.split(','))
<ipython-input-5-717e63366304>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_categories_na_dropped['Categories'] = df_categories_na_dropped['Categories'].apply(lambda x: [i.strip() for i in x] if isinstance(x, list) else x)

['Videojuegos', 'Humor']

In [8]:
df_categories_na_dropped.head()

,Rank,Username,Categories,Suscribers,Country,Visits,Likes,Comments,Links
0,1,tseries,[Música y baile],249500000.0,India,86200.0,2700.0,78.0,http://youtube.com/channel/UCq-Fj5jknLsUf-MWSy...
1,2,MrBeast,"[Videojuegos, Humor]",183500000.0,Estados Unidos,117400000.0,5300000.0,18500.0,http://youtube.com/channel/UCX6OQ3DkcsbYNE6H8u...
2,3,CoComelon,[Educación],165500000.0,Unknown,7000000.0,24700.0,0.0,http://youtube.com/channel/UCbCmjCuTUZos6Inko4...
4,5,KidsDianaShow,"[Animación, Juguetes]",113500000.0,Unknown,3900000.0,12400.0,0.0,http://youtube.com/channel/UCk8GzjMOrta8yxDcKf...
5,6,PewDiePie,"[Películas, Videojuegos]",111500000.0,Estados Unidos,2400000.0,197300.0,4900.0,http://youtube.com/channel/UC-lHJZR3Gqxm24_Vd_...

In [9]:
df=df_categories_na_dropped

In [10]:
genre_translation = {
    'Animación': 'Animation',
    'Animales y mascotas': 'Animals and Pets',
    'ASMR': 'ASMR',
    'Belleza': 'Beauty',
    'Ciencia y tecnología': 'Science and Technology',
    'Coches y vehículos': 'Cars and Vehicles',
    'Comida y bebida': 'Food and Drink',
    'Deportes': 'Sports',
    'Diseño/arte': 'Design/Art',
    'DIY y Life Hacks': 'DIY and Life Hacks',
    'Educación': 'Education',
    'Espectáculos': 'Shows',
    'Fitness': 'Fitness',
    'Humor': 'Comedy',
    'Juguetes': 'Toys',
    'Moda': 'Fashion',
    'Música y baile': 'Music and Dance',
    'Noticias y Política': 'News and Politics',
    'Películas': 'Movies',
    'Salud y autoayuda': 'Health and Self-help',
    'Viajes': 'Travel',
    'Vlogs diarios': 'Daily Vlogs',
    'Videojuegos': 'Video Games'
}

df['Categories'] = df['Categories'].apply(lambda x: [genre_translation[i] for i in x])

In [11]:
df.head()

,Rank,Username,Categories,Suscribers,Country,Visits,Likes,Comments,Links
0,1,tseries,[Music and Dance],249500000.0,India,86200.0,2700.0,78.0,http://youtube.com/channel/UCq-Fj5jknLsUf-MWSy...
1,2,MrBeast,"[Video Games, Comedy]",183500000.0,Estados Unidos,117400000.0,5300000.0,18500.0,http://youtube.com/channel/UCX6OQ3DkcsbYNE6H8u...
2,3,CoComelon,[Education],165500000.0,Unknown,7000000.0,24700.0,0.0,http://youtube.com/channel/UCbCmjCuTUZos6Inko4...
4,5,KidsDianaShow,"[Animation, Toys]",113500000.0,Unknown,3900000.0,12400.0,0.0,http://youtube.com/channel/UCk8GzjMOrta8yxDcKf...
5,6,PewDiePie,"[Movies, Video Games]",111500000.0,Estados Unidos,2400000.0,197300.0,4900.0,http://youtube.com/channel/UC-lHJZR3Gqxm24_Vd_...

In [13]:
df.isnull().any()

Rank          False
Username      False
Categories    False
Suscribers    False
Country       False
Visits        False
Likes         False
Comments      False
Links         False
dtype: bool

In [6]:
import pymongo
from pymongo import MongoClient
con = pymongo.MongoClient("mongodb://localhost:27017/")
db = con.DCSTEC
collection = db.Youtube

In [7]:
data = df.to_dict(orient='records')
collection.insert_many(data)